overwrite: true
schema: 'libs\api\database\graphql\schemas\schema.gql'
generates:
  libs/ui/database/graphql/src/lib/generated-endpoints/person.endpoints.ts:
    documents: 'libs/ui/database/graphql/src/lib/operations/person-operations.gql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-apollo-angular'
